### ISSUE TITLE
import renderer.projector as pj ImportError: No module named projector

### ISSUE THREAD

**Issue by XieZixiUSTC** [pengwangucla/DeLS-3D#4]
would you please help me ,thanks

**Comment by XieZixiUSTC** [comment]
Traceback (most recent call last):
  File "/home/x/ApolloDataSet/DeLS-3D-master/test_DeLS-3D.py", line 18, in <module>
    import utils.dels_utils as de_uts
  File "/home/x/ApolloDataSet/DeLS-3D-master/utils/dels_utils.py", line 204, in <module>
    import renderer.projector as pj
ImportError: No module named projector

Process finished with exit code 1

**Comment by pengwangucla** [comment]
You need to first compile the renderer 

https://github.com/ApolloScapeAuto/dataset-api/tree/master/self_localization/renderer

I use ubuntu14.04, good luck

Best
